### ISSUE TITLE
Curio support

### ISSUE THREAD

**Issue by brettcannon** [encode/httpcore#94]
Other than asyncio and trio, [curio](https://github.com/dabeaz/curio) seems to be the other "big" event loop implementation.

**Comment by tomchristie** [comment]
Well indeed. I’ve not yet reached out to @dabeaz to gauge interest here. The backends are a pretty small amount of code, so it’s probably not going to be a *huge* amount of work if someone’s motivated enough to take it on.

Also, curio isn’t the only other place we could be reaching out to here... We’re following [the lead of the `urllib3` team](https://github.com/python-trio/hip) in our approach here, who had also been looking into providing a Twisted backend too.

I don’t really know anything about that ecosystem, but could be worth reaching out to Amber or Glyph there to figure out if that’s also a valuable avenue to look into.

**Comment by dabeaz** [comment]
I'd definitely be interested in seeing Curio support here, but don't really know what's involved.  Curio recently went through a "version 1.0" release that reduced its set of features to a smaller core and likely broke some things for earlier adopters.  However, I consider the current version of Curio to be stable and more-or-less feature complete.

How would this work?   Should I just submit a drive-by pull request adding Curio support?  (I'm more than happy to have someone else do it if they're motivated though).

**Comment by tomchristie** [comment]
Oh cool, hiya! 👋

> but don't really know what's involved

Implementing a concurrency backend requires implementing the `AsyncBackend` interface... https://github.com/encode/httpcore/blob/master/httpcore/_backends/base.py

That provides the bare bones for "give me a semaphore", "give me a lock", and "open a TCP stream", which is everything the backend needs to provide.

The [asyncio](https://github.com/encode/httpcore/blob/master/httpcore/_backends/asyncio.py) and [trio](https://github.com/encode/httpcore/blob/master/httpcore/_backends/trio.py) implementations are worth a quick look over, as the two existing async examples. (There's an equivalent sync implementation too.)

Once there's an implementation, the other bit is to tie it in with the concurrency autodetection... https://github.com/encode/httpcore/blob/master/httpcore/_backends/auto.py#L17-L28 

For the tests I think it'd be a case of adding curio to https://github.com/encode/httpcore/blob/master/tests/conftest.py#L15-L20 in order to include it in the test parameterization, but I don't recall off the top of my head if there's more beyond that to do.

> Should I just submit a drive-by pull request adding Curio support?

That'd be pretty fantastic if you're up for it.

**Comment by brettcannon** [comment]
I would be happy to help @dabeaz out if I can (which doesn't count for much these days with so many OSS projects on the go right now and thus nearly no spare time 😄).

And doing a [search for the word "trio"](https://github.com/encode/httpcore/search?q=trio&unscoped_q=trio) suggests that what @tomchristie outlined covers nearly everything but packaging details (there was a hit on an `unasync` module).

**Comment by brettcannon** [comment]
@cdeler I am not working on this, so feel free to go for it!
